name: "Check Provider Bitmaps"
description: "Checkout that the onchai provider bitmaps are in sync with the configuration in the code"

inputs:
  ALCHEMY_API_KEY_OP:
    description: "Alchemy API key for Optimism"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check Optimism Onchain Provider Bitmaps
      run: |
        echo "📋📋📋 Check Optimism Onchain Provider Bitmaps"
        yarn workspace @gitcoin/passport-iam checkProviders:op
      shell: bash
      env:
        ALCHEMY_API_KEY: ${{ inputs.ALCHEMY_API_KEY_OP }}
    - name: Check Optimism Sepolia Onchain Provider Bitmaps
      run: |
        echo "📋📋📋 Check Optimism Sepolia Onchain Provider Bitmaps"
        yarn workspace @gitcoin/passport-iam checkProviders:op-sepolia
      shell: bash
      env:
        ALCHEMY_API_KEY: ${{ inputs.ALCHEMY_API_KEY_OP }}
    - name: Check Arbitrum Onchain Provider Bitmaps
      run: |
        echo "📋📋📋 Check Arbitrum  Onchain Provider Bitmaps"
        yarn workspace @gitcoin/passport-iam checkProviders:arb
      shell: bash
      env:
        ALCHEMY_API_KEY: ${{ inputs.ALCHEMY_API_KEY_OP }}
    - name: Check Arbitrum Onchain Provider Bitmaps
      run: |
        echo "📋📋📋 Check ZkSync Onchain Provider Bitmaps"
        yarn workspace @gitcoin/passport-iam checkProviders:zksync
      shell: bash
      env:
        ALCHEMY_API_KEY: ${{ inputs.ALCHEMY_API_KEY_OP }}
    - name: Check Scroll Onchain Provider Bitmaps
      run: |
        echo "📋📋📋 Check Scroll Onchain Provider Bitmaps"
        yarn workspace @gitcoin/passport-iam checkProviders:scroll
      shell: bash
      env:
        ALCHEMY_API_KEY: ${{ inputs.ALCHEMY_API_KEY_OP }}
    - name: Check Linea Onchain Provider Bitmaps
      run: |
        echo "📋📋📋 Check Scroll Onchain Provider Bitmaps"
        yarn workspace @gitcoin/passport-iam checkProviders::linea
      shell: bash
      env:
        ALCHEMY_API_KEY: ${{ inputs.ALCHEMY_API_KEY_OP }}