name: CI - build & test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    # Run a local ceramic nod to test against
    services:
      ceramic:
        image: gitcoinpassport/js-ceramic:3.2.0
        ports:
          - 7007:7007

    steps:
      - uses: ./github/actions/test.yml
