name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    # Run a local ceramic nod to test against
    services:
      ceramic:
        image: ceramicnetwork/js-ceramic:2.20.0
        ports:
          - 7007:7007

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Install Packages
        run: yarn install
      # - name: Run Tests
      #   run: yarn test
      # - name: Run Linter
      #   run: yarn lint
      - name: Workarround for build error
        run: rm -rf node_modules/@tendermint
      # - name: Run Build (ensure that build succeeds)
      #   run: yarn build
      # - name: Run Ceramic Integration Tests
      #   run: yarn test:ceramic-integration
      - name: Git fetch
        run: |
          git fetch
          git show origin/main:iam/src/static/providerBitMapInfo.json
        working-directory: ./iam
      - name: Check bitmap against main
        run: |
          node dist/iam/src/scripts/checkProviderBitMapInfoAgaistMain.js origin/main
        working-directory: ./iam
      - name: Check not providers are missing from bitmap
        run: |
          node dist/iam/src/scripts/checkProviderBitMapInfoForMissingProviders.js
        working-directory: ./iam
