name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    # Run a local ceramic nod to test against
    services:
      ceramic:
        image: gitcoinpassport/js-ceramic:3.2.0
        ports:
          - 7007:7007

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.8.1
          cache: "yarn"
      - name: Install Packages
        run: yarn install
      - name: Run Tests
        run: yarn test
      - name: Run Linter
        run: yarn lint
      - name: Workarround for build error
        run: rm -rf node_modules/@tendermint
      - name: Run Build (ensure that build succeeds)
        run: yarn build
      - name: Deploy Ceramic Models
        working-directory: ./schemas
        run: yarn models:deploy-composite
        env:
          CERAMIC_URL: http://localhost:7007
          PRIVATE_KEY: ${{secrets.CERAMIC_PRIVATE_KEY}}
      - name: Run Ceramic Integration Tests
        run: yarn test:ceramic-integration
        env:
          CERAMIC_CLIENT_URL: http://localhost:7007

  check-provider-bitmap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          DATA_SCIENCE_API_URL: op://DevOps/passport-review/iam/DATA_SCIENCE_API_URL
          ALCHEMY_API_KEY_OP_SEPOLIA: op://DevOps/passport-review/iam/ALCHEMY_API_KEY_OP_SEPOLIA
          ALCHEMY_API_KEY_OP: op://DevOps/passport-review/iam/ALCHEMY_API_KEY_OP

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.8
          cache: "yarn"
      - name: Install Packages
        run: yarn install
      - name: Check provider bitmaps
        uses: ./.github/actions/check-provider-bitmaps
        with:
          ALCHEMY_API_KEY_OP: ${{ env.ALCHEMY_API_KEY_OP }}
          ALCHEMY_API_KEY_OP_SEPOLIA: ${{ env.ALCHEMY_API_KEY_OP_SEPOLIA }}
