name: Deploy to Review

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit ref"
        required: true
        default: "main"
        type: string

jobs:
  deploy-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: review-test-github-actions # TODO change back to `review`
      - name: Fast forward merge
        run: git merge --ff-only ${{ commit }}
      - name: Push to Github Repo
        run: git push origin
