name: Deploy UI to Review

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Leave blank to use current HEAD, or provide an override commit SHA"
        type: string
        required: false

jobs:
  ref:
    name: Load Commit Ref
    runs-on: ubuntu-latest
    steps:
      - id: ref
        uses: passportxyz/gh-workflows/.github/actions/load_commit_ref@v1
        with:
          commit: ${{ inputs.commit }}

    outputs:
      version_tag: ${{ steps.ref.outputs.version_tag }}
      docker_tag: ${{ steps.ref.outputs.docker_tag }}
      refspec: ${{ steps.ref.outputs.refspec }}

  # TODO: run tests ?
  deploy-ui:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.ref.outputs.refspec }}
          fetch-depth: 0
      - name: Push code to branch
        uses: passportxyz/gh-workflows/.github/actions/push_to_branch@v1
        with:
          commit: ${{ needs.ref.outputs.refspec }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: production-interface
