name: Deploy API to Staging
on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Leave blank to use current HEAD, or provide an override commit SHA"
        type: string

jobs:
  ref:
    name: Load Commit Ref
    runs-on: ubuntu-latest
    steps:
      - id: ref
        uses: passportxyz/gh-workflows/.github/actions/load_commit_ref@v1
        with:
          commit: ${{ inputs.commit }}

    outputs:
      version_tag: ${{ steps.ref.outputs.version_tag }}
      docker_tag: ${{ steps.ref.outputs.docker_tag }}
      refspec: ${{ steps.ref.outputs.refspec }}

  check-provider-bitmap:
    runs-on: ubuntu-latest
    needs: [ref]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.8
          cache: "yarn"
      - name: Install Packages
        run: yarn install
      - name: Check provider bitmaps
        uses: ./.github/actions/check-provider-bitmaps
        with:
          ALCHEMY_API_KEY_OP: op://DevOps/passport-staging-secrets/ci/ALCHEMY_API_KEY_OP
          ALCHEMY_API_KEY_OP_SEPOLIA: op://DevOps/passport-staging-secrets/ci/ALCHEMY_API_KEY_OP_SEPOLIA

  deploy:
    name: Deploy to Staging
    needs: [ref, check-provider-bitmap]
    uses: ./.github/workflows/deploy_generic.yml
    with:
      refspec: ${{ needs.ref.outputs.refspec }}
      docker_tag: ${{ needs.ref.outputs.docker_tag }}
      environment: staging
    secrets: inherit
